### ISSUE TITLE
400 when generating a certificate for Azure

### ISSUE THREAD

**Issue by DinoSourcesRex** [terraform-providers/terraform-provider-acme#5] opened 2018-08-17 13:05 UTC
I took the example from [here](https://www.terraform.io/docs/providers/acme/r/certificate.html#example) and modified it to use Azure for the dns challenge. The main.tf is below, you will only need to supply azure details and an email.

Any advice on how to proceed would be welcome.

```terraform
provider "acme" {
  server_url = "https://acme-staging-v02.api.letsencrypt.org/directory"
}

# Create the resource group
resource "azurerm_resource_group" "environment" {
  name     = "certest-rg"
  location = "West Europe"
}

resource "tls_private_key" "private_key" {
  algorithm = "RSA"
}

resource "acme_registration" "reg" {
  account_key_pem = "${tls_private_key.private_key.private_key_pem}"
  email_address   = "email@example.com"
}

resource "acme_certificate" "certificate" {
  account_key_pem           = "${acme_registration.reg.account_key_pem}"
  common_name               = "www.example.com"
  subject_alternative_names = ["www2.example.com"]

  dns_challenge {
    provider = "azure"

    config {
      AZURE_CLIENT_ID         = ""
      AZURE_CLIENT_SECRET     = ""
      AZURE_SUBSCRIPTION_ID   = ""
      AZURE_TENANT_ID         = ""
      AZURE_RESOURCE_GROUP    = "${azurerm_resource_group.environment.id}"
    }
  }
}
```

And the error.

```
Error: Error applying plan:

1 error(s) occurred:

* acme_certificate.certificate: 1 error(s) occurred:

* acme_certificate.certificate: error creating certificate: acme: Error -> One or more domains had a problem:
[www2.example.com] Error presenting token: dns.ZonesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2017-09-01' is invalid. The supported versions are '2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
[www.example.com] Error presenting token: dns.ZonesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2017-09-01' is invalid. The supported versions are '2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```

**Comment by vancluever** [comment] 2018-08-29 19:52
@DinoSourcesRex I've been trying to reproduce this at a base level and have not been able to 100% yet. Also, there does not seem to be any related issues in https://github.com/xenolf/lego. I still need to test this 100% - the barrier to entry right now for a 100% repro is delegating a DNS zone for use with Azure on our end as we run our tests in AWS. What I have managed to test is that I'm _actually_ able to connect to Azure on our end here and get a "zone not found" error. I'm not too sure if that's enough to fully confirm that the API version mismatch isn't reproducible.

What location were you testing it in? I'm not too sure it that will make a difference but it will help with the repro.

Thanks!

**Comment by DinoSourcesRex** [comment] 2018-08-29 20:48
@vancluever Hey there, Embarrassingly I don't remember. I am fairly sure what is in here is my full `main.tf`, so you've got everything I had at the time.

**Comment by vancluever** [comment] 2019-02-18 16:41
Closing this issue due to age and a lack of repro.

**Closed by vancluever** 2019-02-18 16:41 UTC
